[package]
name = "random-problems"
version = "0.1.0"
edition = "2021"

[dependencies]
minreq = { version = "2.12.0", features = ["https"] }
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
